#!/bin/bash

ffmpeg -r 60 -f image2 -s 640x480 -i $1/cam0_image%05d.png -vcodec libx264 -crf 25  -pix_fmt yuv420p cam0.mp4

ffmpeg -r 60 -f image2 -s 640x480 -i $1/cam1_image%05d.png -vcodec libx264 -crf 25  -pix_fmt yuv420p cam1.mp4
